# Generated by Django 3.2 on 2021-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='img')),
                ('comment', models.IntegerField()),
                ('ty', models.CharField(choices=[('AI', 'AI'), ('pro', 'pro'), ('high', 'high'), ('new', 'new'), ('old', 'old')], default='AI', max_length=50)),
                ('feature', models.BooleanField(default=False)),
            ],
        ),
    ]
